<<<<<<< HEAD
runtime: python27
api_version: 1
threadsafe: true
vm: true

handlers:
- url: .*
  script: main.app
=======
runtime: python27
api_version: 1
threadsafe: true
vm: true
handlers:
- url: /.*
  script: main.app
skip_files:
  - ^node_modules/.*
>>>>>>> 54bbc9c17870dc2966fe24799ebfcc93d3d44c8f
